import type { NextApiRequest, NextApiResponse } from "next";
import PDFDocument from "pdfkit";
import * as Sentry from "@sentry/nextjs";

const MAX_ANALYSIS_LENGTH = 50000; // Förhindra extremt stora PDFs

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== "POST") return res.status(405).end();

  const { analysis, riskLevel } = req.body;

  // ⚠️ KRITISK FIX: Validering
  if (!analysis || !riskLevel) {
    return res.status(400).json({ error: "Missing analysis data" });
  }

  if (typeof analysis !== 'string' || typeof riskLevel !== 'string') {
    return res.status(400).json({ error: "Invalid data format" });
  }

  if (analysis.length > MAX_ANALYSIS_LENGTH) {
    return res.status(400).json({ 
      error: "Analysis too large for PDF export" 
    });
  }

  try {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      bufferPages: true, // ⚠️ FIX: Förhindra minnesläckor
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      'attachment; filename="TrustTerms_Contract_Analysis.pdf"'
    );

    // ⚠️ KRITISK FIX: Error handling för PDF stream
    doc.on('error', (err) => {
      console.error('PDF generation error:', err);
      Sentry.captureException(err, {
        tags: { api_route: 'export-pdf' },
      });
      if (!res.headersSent) {
        res.status(500).json({ error: "PDF generation failed" });
      }
    });

    doc.pipe(res);

    // Title
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("TrustTerms – Contract Risk Analysis");

    doc.moveDown();

    // Risk badge
    const riskColor =
      riskLevel === "HIGH"
        ? "#DC2626"
        : riskLevel === "MEDIUM"
        ? "#EA580C"
        : "#16A34A";

    doc
      .fontSize(14)
      .fillColor(riskColor)
      .font("Helvetica-Bold")
      .text(`Overall risk level: ${riskLevel}`);

    doc.moveDown();
    doc.fillColor("black").font("Helvetica").fontSize(11);

    // Analysis body - ⚠️ FIX: Hantera långa texter
    const maxLineLength = 90;
    const lines = analysis.split('\n');
    
    for (const line of lines) {
      if (line.length > maxLineLength) {
        // Dela upp långa rader
        const words = line.split(' ');
        let currentLine = '';
        
        for (const word of words) {
          if ((currentLine + word).length > maxLineLength) {
            doc.text(currentLine.trim(), { lineGap: 4 });
            currentLine = word + ' ';
          } else {
            currentLine += word + ' ';
          }
        }
        
        if (currentLine) {
          doc.text(currentLine.trim(), { lineGap: 4 });
        }
      } else {
        doc.text(line, { lineGap: 4 });
      }
    }

    doc.moveDown(2);

    // Disclaimer med bättre formatering
    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "DISCLAIMER: This analysis is generated by an AI system for informational purposes only and does not constitute legal advice. The analysis may contain errors or omissions. Always consult a qualified lawyer before making legal decisions or signing contracts.",
        {
          align: 'left',
          lineGap: 3,
        }
      );

    doc.moveDown();

    // Footer med datum
    doc
      .fontSize(8)
      .fillColor("#6B7280")
      .text(
        `Generated: ${new Date().toLocaleString('sv-SE')} | TrustTerms.vercel.app`,
        {
          align: 'center',
        }
      );

    doc.end();

  } catch (err: any) {
    console.error('❌ PDF export error:', err);
    
    Sentry.captureException(err, {
      tags: {
        api_route: 'export-pdf',
      },
      extra: {
        analysis_length: analysis?.length,
        risk_level: riskLevel,
      },
    });

    if (!res.headersSent) {
      res.status(500).json({ error: "PDF generation failed. Please try again." });
    }
  }
}