import type { NextApiRequest, NextApiResponse } from "next";
import PDFDocument from "pdfkit";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== "POST") return res.status(405).end();

  const { analysis, riskLevel } = req.body;

  if (!analysis || !riskLevel) {
    return res.status(400).json({ error: "Missing analysis data" });
  }

  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    'attachment; filename="TrustTerms_Contract_Analysis.pdf"'
  );

  doc.pipe(res);

  // Title
  doc
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("TrustTerms – Contract Risk Analysis");

  doc.moveDown();

  // Risk badge
  const riskColor =
    riskLevel === "HIGH"
      ? "red"
      : riskLevel === "MEDIUM"
      ? "orange"
      : "green";

  doc
    .fontSize(14)
    .fillColor(riskColor)
    .font("Helvetica-Bold")
    .text(`Overall risk level: ${riskLevel}`);

  doc.moveDown();
  doc.fillColor("black").font("Helvetica").fontSize(11);

  // Analysis body
  doc.text(analysis, {
    lineGap: 4,
  });

  doc.moveDown(2);

  // Disclaimer
  doc
    .fontSize(9)
    .fillColor("gray")
    .text(
      "Disclaimer: This analysis is generated by an AI system for informational purposes only and does not constitute legal advice. Always consult a qualified lawyer before making legal decisions."
    );

  doc.end();
}